---
title: "golden_globes_google_trends_viz"
format: html
---
```{r}
library(tidyverse)
library(patchwork)
```

# 1
# Zoe Saldaña
```{r}
# 1
# Zoe Saldaña
zoe_saldana <- read_csv("golden_globes_google_trends/data/zoe_saldana.csv", skip = 1)

zoe_saldana_plot <- zoe_saldana |> 
  rename(time = 1, score = 2) |>
  mutate(score = if_else(score == "<1", "0", score),
         score = as.numeric(score)) |>
    filter(time >= as.POSIXct("2025-01-06 01:00:00", tz = "UTC") &
         time <= as.POSIXct("2025-01-06 04:30:00", tz = "UTC")) |>
  mutate(row_num = row_number()) |>
  ggplot(aes(x = row_num, y = score)) +
  geom_line(lwd = 1.9, color = "#112b41") +
    theme(
    axis.title = element_blank(),  # Remove axis titles
    axis.text = element_blank(),   # Remove axis text
    axis.ticks = element_blank(),  # Remove axis ticks
    panel.background = element_rect(fill = "white"),
        plot.margin = margin(t = 0, r = 0, b = 0, l = 0)  # Adjust top and bottom margins (t = top, b = bottom)
  )
  
```

# 2
# Jean Smart
```{r}
# 2
# Jean Smart
jean_smart <- read_csv("golden_globes_google_trends/data/jean_smart.csv", skip = 1)

jean_smart_plot <- jean_smart |> 
  rename(time = 1, score = 2) |>
    filter(time >= as.POSIXct("2025-01-06 01:00:00", tz = "UTC") &
         time <= as.POSIXct("2025-01-06 04:30:00", tz = "UTC")) |>
  mutate(row_num = row_number()) |>
  ggplot(aes(x = row_num, y = score)) +
  geom_line(lwd = 1.9, color = "#16344d") +
    theme(
    axis.title = element_blank(),  # Remove axis titles
    axis.text = element_blank(),   # Remove axis text
    axis.ticks = element_blank(),  # Remove axis ticks
    panel.background = element_rect(fill = "white"),
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0) 
  )
  
  
```

# 3
# Kieran Culkin
```{r}
# 3
# Kieran Culkin
kieran_culkin <- read_csv("golden_globes_google_trends/data/kieran_culkin.csv", skip = 1)

kieran_culkin_plot <- kieran_culkin |> 
  rename(time = 1, score = 2) |>
    filter(time >= as.POSIXct("2025-01-06 01:00:00", tz = "UTC") &
         time <= as.POSIXct("2025-01-06 04:30:00", tz = "UTC")) |>
  mutate(row_num = row_number()) |>
  ggplot(aes(x = row_num, y = score)) +
  geom_line(lwd = 1.9, color = "#1b3d5a") +
    theme(
    axis.title = element_blank(),  # Remove axis titles
    axis.text = element_blank(),   # Remove axis text
    axis.ticks = element_blank(),  # Remove axis ticks
    panel.background = element_rect(fill = "white"),
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0) 
  )
  
  
```


# 4
# Hiroyuki Sanada
```{r}
# 4
# Hiroyuki Sanada
hiroyuki_sanada <- read_csv("golden_globes_google_trends/data/hiroyuki_sanada.csv", skip = 1)

hiroyuki_sanada_plot <- hiroyuki_sanada |> 
  rename(time = 1, score = 2) |>
    filter(time >= as.POSIXct("2025-01-06 01:00:00", tz = "UTC") &
         time <= as.POSIXct("2025-01-06 04:30:00", tz = "UTC")) |>
  mutate(row_num = row_number()) |>
  ggplot(aes(x = row_num, y = score)) +
  geom_line(lwd = 1.9, color = "#204767") +
    theme(
    axis.title = element_blank(),  # Remove axis titles
    axis.text = element_blank(),   # Remove axis text
    axis.ticks = element_blank(),  # Remove axis ticks
    panel.background = element_rect(fill = "white"),
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0) 
  )
  
  
```


# 5
# Jessica Gunning
```{r}
# 5
# Jessica Gunning
jessica_gunning <- read_csv("golden_globes_google_trends/data/jessica_gunning.csv", skip = 1)

jessica_gunning_plot <- jessica_gunning |> 
  rename(time = 1, score = 2) |>
    filter(time >= as.POSIXct("2025-01-06 01:00:00", tz = "UTC") &
         time <= as.POSIXct("2025-01-06 04:30:00", tz = "UTC")) |>
  mutate(row_num = row_number()) |>
  ggplot(aes(x = row_num, y = score)) +
  geom_line(lwd = 1.9, color = "#255175") +
    theme(
    axis.title = element_blank(),  # Remove axis titles
    axis.text = element_blank(),   # Remove axis text
    axis.ticks = element_blank(),  # Remove axis ticks
    panel.background = element_rect(fill = "white"),
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0) 
  )
  
```


# 6
# Tadanobu Asano
```{r}
# 6
# Tadanobu Asano
tadanobu_asano <- read_csv("golden_globes_google_trends/data/tadanobu_asano.csv", skip = 1)

tadanobu_asano_plot <- tadanobu_asano |> 
  rename(time = 1, score = 2) |>
    filter(time >= as.POSIXct("2025-01-06 01:00:00", tz = "UTC") &
         time <= as.POSIXct("2025-01-06 04:30:00", tz = "UTC")) |>
  mutate(row_num = row_number()) |>
  ggplot(aes(x = row_num, y = score)) +
  geom_line(lwd = 1.9, color = "#2a5b82") +
    theme(
    axis.title = element_blank(),  # Remove axis titles
    axis.text = element_blank(),   # Remove axis text
    axis.ticks = element_blank(),  # Remove axis ticks
    panel.background = element_rect(fill = "white"),
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0) 
  )
  
```

# 7
# Jeremy Allen White
```{r}
# 7
# Jeremy Allen White
jeremy_allen_white <- read_csv("golden_globes_google_trends/data/jeremy_allen_white.csv", skip = 1)

jeremy_allen_white_plot <- jeremy_allen_white |> 
  rename(time = 1, score = 2) |>
    filter(time >= as.POSIXct("2025-01-06 01:00:00", tz = "UTC") &
         time <= as.POSIXct("2025-01-06 04:30:00", tz = "UTC")) |>
  mutate(row_num = row_number()) |>
  ggplot(aes(x = row_num, y = score)) +
  geom_line(lwd = 1.9, color = "#2f6590") +
    theme(
    axis.title = element_blank(),  # Remove axis titles
    axis.text = element_blank(),   # Remove axis text
    axis.ticks = element_blank(),  # Remove axis ticks
    panel.background = element_rect(fill = "white"),
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0) 
  )
```

# 8
# Colin Farrell
```{r}
# 8
# Colin Farrell
colin_farrell <- read_csv("golden_globes_google_trends/data/colin_farrell.csv", skip = 1)

colin_farrell_plot <- colin_farrell |> 
  rename(time = 1, score = 2) |>
  mutate(score = if_else(score == "<1", "0", score),
         score = as.numeric(score)) |>
    filter(time >= as.POSIXct("2025-01-06 01:00:00", tz = "UTC") &
         time <= as.POSIXct("2025-01-06 04:30:00", tz = "UTC")) |>
  mutate(row_num = row_number()) |>
  ggplot(aes(x = row_num, y = score)) +
  geom_line(lwd = 1.9, color = "#346f9e") +
    theme(
    axis.title = element_blank(),  # Remove axis titles
    axis.text = element_blank(),   # Remove axis text
    axis.ticks = element_blank(),  # Remove axis ticks
    panel.background = element_rect(fill = "white"),
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0) 
  )
  
```


# 9
# Jodie Foster
```{r}
# 9
# Jodie Foster
jodie_foster <- read_csv("golden_globes_google_trends/data/jodie_foster.csv", skip = 1)

jodie_foster_plot <- jodie_foster |> 
  rename(time = 1, score = 2) |>
  mutate(score = if_else(score == "<1", "0", score),
         score = as.numeric(score)) |>
    filter(time >= as.POSIXct("2025-01-06 01:00:00", tz = "UTC") &
         time <= as.POSIXct("2025-01-06 04:30:00", tz = "UTC")) |>
  mutate(row_num = row_number()) |>
  ggplot(aes(x = row_num, y = score)) +
  geom_line(lwd = 1.9, color = "#397aad") +
    theme(
    axis.title = element_blank(),  # Remove axis titles
    axis.text = element_blank(),   # Remove axis text
    axis.ticks = element_blank(),  # Remove axis ticks
    panel.background = element_rect(fill = "white"),
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0) 
  )
  
```

# 10
# Demi Moore
```{r}
# 10
# Demi Moore
demi_moore <- read_csv("golden_globes_google_trends/data/demi_moore.csv", skip = 1)

demi_moore_plot <- demi_moore |> 
  rename(time = 1, score = 2) |>
    filter(time >= as.POSIXct("2025-01-06 01:00:00", tz = "UTC") &
         time <= as.POSIXct("2025-01-06 04:30:00", tz = "UTC")) |>
  mutate(row_num = row_number()) |>
  ggplot(aes(x = row_num, y = score)) +
  geom_line(lwd = 1.9, color = "#3f84bc") +
    theme(
    axis.title = element_blank(),  # Remove axis titles
    axis.text = element_blank(),   # Remove axis text
    axis.ticks = element_blank(),  # Remove axis ticks
    panel.background = element_rect(fill = "white"),
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0) 
  )
```

# 11
# Sebastian Stan
```{r}
# 11
# Sebastian Stan
sebastian_stan <- read_csv("golden_globes_google_trends/data/sebastian_stan.csv", skip = 1)

sebastian_stan_plot <- sebastian_stan |> 
  rename(time = 1, score = 2) |>
  mutate(score = if_else(score == "<1", "0", score),
         score = as.numeric(score)) |>
    filter(time >= as.POSIXct("2025-01-06 01:00:00", tz = "UTC") &
         time <= as.POSIXct("2025-01-06 04:30:00", tz = "UTC")) |>
  mutate(row_num = row_number()) |>
  ggplot(aes(x = row_num, y = score)) +
  geom_line(lwd = 1.9, color = "#448fca") +
    theme(
    axis.title = element_blank(),  # Remove axis titles
    axis.text = element_blank(),   # Remove axis text
    axis.ticks = element_blank(),  # Remove axis ticks
    panel.background = element_rect(fill = "white"),
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0) 
  )
  
```

# 12
# Anna Sawai
```{r}
# 12
# Anna Sawai
anna_sawai <- read_csv("golden_globes_google_trends/data/anna_sawai.csv", skip = 1)

anna_sawai_plot <- anna_sawai |> 
  rename(time = 1, score = 2) |>
    filter(time >= as.POSIXct("2025-01-06 01:00:00", tz = "UTC") &
         time <= as.POSIXct("2025-01-06 04:30:00", tz = "UTC")) |>
  mutate(row_num = row_number()) |>
  ggplot(aes(x = row_num, y = score)) +
  geom_line(lwd = 1.9, color = "#499ad9") +
    theme(
    axis.title = element_blank(),  # Remove axis titles
    axis.text = element_blank(),   # Remove axis text
    axis.ticks = element_blank(),  # Remove axis ticks
    panel.background = element_rect(fill = "white"),
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0) 
  )
```


# 13
# Fernanda Torres
```{r}
# 13
# Fernanda Torres
fernanda_torres <- read_csv("golden_globes_google_trends/data/fernanda_torres.csv", skip = 1)

fernanda_torres_plot <- fernanda_torres |> 
  rename(time = 1, score = 2) |>
    filter(time >= as.POSIXct("2025-01-06 01:00:00", tz = "UTC") &
         time <= as.POSIXct("2025-01-06 04:30:00", tz = "UTC")) |>
  mutate(row_num = row_number()) |>
  ggplot(aes(x = row_num, y = score)) +
  geom_line(lwd = 1.9, color = "#4fa6e9") +
    theme(
    axis.title = element_blank(),  # Remove axis titles
    axis.text = element_blank(),   # Remove axis text
    axis.ticks = element_blank(),  # Remove axis ticks
    panel.background = element_rect(fill = "white"),
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0) 
  ) 
```


# 14
#Adrien Brody
```{r}
# 14
#Adrien Brody
adrien_brody <- read_csv("golden_globes_google_trends/data/adrien_brody.csv", skip = 1)

adrien_brody_plot  <- adrien_brody |> 
  rename(time = 1, score = 2) |>
  mutate(score = if_else(score == "<1", "0", score),
         score = as.numeric(score)) |>
    filter(time >= as.POSIXct("2025-01-06 01:00:00", tz = "UTC") &
         time <= as.POSIXct("2025-01-06 04:30:00", tz = "UTC")) |>
  mutate(row_num = row_number()) |>
    ggplot(aes(x = row_num, y = score)) +
  geom_line(lwd = 1.9, color = "#54b1f8") +
    theme(
    axis.title = element_blank(),  # Remove axis titles
    axis.text = element_blank(),   # Remove axis text
    axis.ticks = element_blank(),  # Remove axis ticks
    panel.background = element_rect(fill = "white"),
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0) 
  )
```


```{r}
test <- zoe_saldana_plot / jean_smart_plot / kieran_culkin_plot / hiroyuki_sanada_plot / jessica_gunning_plot / tadanobu_asano_plot / jeremy_allen_white_plot / colin_farrell_plot / jodie_foster_plot / demi_moore_plot / sebastian_stan_plot / anna_sawai_plot / fernanda_torres_plot / adrien_brody_plot

test
```
