---
title: "mlb_first_pitch_time_viz"
format: html
---

```{r}
library(tidyverse)
```

```{r}
mlb_schedule_2025_raw <- read_csv("sports/baseball/mlb_team_start_times/data/mlb_schedule_2025.csv")

mlb_schedule_2025 <- mlb_schedule_2025_raw |>
  mutate(
    Time = str_extract(`Local Start Time`, "\\d{1,2}:\\d{2} [AP]M"),
    TimeZone = str_extract(`Local Start Time`, "(?<=\\d{1,2}:\\d{2} [AP]M )\\S+")
  )

```

```{r}
# individual team level:
mlb_schedule_2025 %>%
  filter(`Home Team` == "Chicago Cubs") %>%   # only home games
  count(Time, name = "Games") %>%              # count occurrences of each Time
  arrange(desc(Games))   


home_team_common_times <- mlb_schedule_2025 %>%
  group_by(`Home Team`, Time) %>%        # group by home team and start time
  summarise(Games = n(), .groups = "drop") %>%  # count games at each time
  group_by(`Home Team`) %>%
  slice_max(Games, n = 1, with_ties = FALSE) |> print(n=32)

home_times_summary <- home_team_common_times |> group_by(Time) |>
  summarise(count = n()) |>
  arrange(desc(count)) |>
  mutate(Time = sub("^0", "", Time)) # remove the leading 0 in the time dim
  

```











```{r}
ggplot(home_times_summary, aes(x = Time, y = count)) +
  geom_col(fill = "gray90", color = "gray40", linewidth = 1) +
  labs(
    title = "Most Common Home Start Times for MLB Teams",
    x = element_blank(),
    y = NULL,
    caption = "Source: 2025 MLB Schedule                                        sudo_masochist"
  ) +
  scale_y_continuous(breaks = c(5, 10, 15)) +  # exclude 0
  theme_minimal(base_family = "Menlo", base_size = 12) +
  theme(
    plot.title = element_text(face = "bold", size = rel(1.6), hjust = 0.5, margin = margin(b = 0)),
    plot.title.position = "plot",
    plot.caption = element_text(size = rel(0.9), color = "gray40", hjust = 0),
    plot.caption.position = "plot",

    axis.title.y = element_blank(),
    axis.text = element_text(size = rel(0.9), color = "gray20"),

    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(color = "gray80", linewidth = 0.4),

    axis.ticks = element_blank(),
    axis.line = element_blank(),

    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA),

    plot.margin = margin(20, 10, 10, 10),
    axis.text.x = element_text(angle = 45, hjust = 1, size = rel(1.2))
  )


ggsave(
  "sports/baseball/mlb_team_start_times/mlb_team_start_times.png",
  plot = last_plot(),
  width = 7,
  height = 7,
  units = "in",
  dpi = 300,
  bg = "white"
)


```

```{r}
ggplot(home_times_summary, aes(x = Time, y = count)) +
  geom_col(fill = "gray90", color = "gray40", linewidth = 1) +
  labs(
    title = "Most Common Home Start Times for MLB Teams",
    x = element_blank(),
    y = NULL,
    caption = "Source: MLB Schedule                                        sudo_masochist"
  ) +
  scale_y_continuous(breaks = c(5, 10, 15)) +  # exclude 0
  theme_minimal(base_family = "Menlo", base_size = 12) +
  theme(
    plot.title = element_text(face = "bold", size = rel(1.6), hjust = 0.5, margin = margin(b = 0)),
    plot.title.position = "plot",
    plot.caption = element_text(size = rel(0.9), color = "gray40", hjust = 0),
    plot.caption.position = "plot",

    axis.title.y = element_blank(),
    axis.text = element_text(size = rel(0.9), color = "gray20"),

    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(color = "gray80", linewidth = 0.4),

    axis.ticks = element_blank(),
    axis.line = element_blank(),

    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA),

    plot.margin = margin(20, 10, 10, 10),
    axis.text.x = element_text(angle = 45, hjust = 1, size = rel(1.2))
  )


```

